version: '3.9'

services:
  python-app:
    build: 
     context: .
    container_name: python-app
    volumes:
      - ./app:/app  # Monte uniquement le dossier app
    env_file:
      - .env        # Charge le fichier d'environnement