services:
  python-app:
    build: 
      context: .
    container_name: python-app
    depends_on:
      - postgres  # Ensure postgres is up before the python app starts
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=my_database
      - DB_USER=my_user
      - DB_PASSWORD=my_password
    volumes:
      - ./app:/app
    env_file:
      - .env
    command: >
      bash -c "python api_handler.py && 
               python data_transformer.py &&
               python db_loader.py"


  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_USER=my_user
      - POSTGRES_DB=my_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
