version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  webserver:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: "my-fernet-key"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres:5432/airflow"
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    command: webserver
    volumes:
    - ./dags:/opt/airflow/dags
    - ./app:/app

  scheduler:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - webserver
      - postgres
    command: scheduler
    volumes:
    - ./dags:/opt/airflow/dags
    - ./app:/app
